### PR TITLE
22.3.0 update

### PR DESCRIPTION
**Pull request by takeda**
### Description

Merged black 22.3.0. Also fixes click incompatibility.

### Checklist - did you ...

- [ ] Add a CHANGELOG entry if necessary?
- [ ] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

### CODE REVIEW

**Comment by takeda** [comment]
@jleclanche can this be merged? Or do you prefer to rebase change on top? I merged the update, because it doesn't mess up with people who checked the repo out, but I can do rebase instead.

**Comment by jleclanche** [comment]
@takeda I'd prefer if you rebased the few commits we have on top of their master branch.

**Comment by takeda** [comment]
@jleclanche I rebased it, but since it is a rebase then it requires force push to master (that's why these conflicts are showing up), which I was trying to avoid doing.

**Comment by takeda** [comment]
I would still recommend to reconsider using merge next time, it makes the maintenance much easier and minimizes conflicts in the future. The old commits can still be fished out via `git log` (forgot exact parameters but maybe it was `git log --cherry <upstream>...<ours>` ) or bubbled up via `git rebase`

**Comment by jleclanche** [comment]
Sorry, this fell off my radar. Merged. Do you want to do a release?

**Comment by takeda** [comment]
@jleclanche I don't think I can do that, I don't have permissions.

I believe you can release it by performing these steps:

https://github.com/jleclanche/tan/issues/11#issuecomment-1016977551

**Pull request merged**
